service: expressless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: dist/http/http-serverless.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
